import "./globals.css";

import type { Metadata } from "next";
import MouseAnimation from "./components/layout/MouseAnimation";

export const metadata: Metadata = {
  title: "tradetoday",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen`}
      >
        <MouseAnimation />
        {children}
      </body>
    </html>
  );
}
